// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj5zfWVZqS9Dg5s0lu7v1tJfjZSZwd32E',
    appId: '1:185894325619:web:b0e880e6bc7649f9f38906',
    messagingSenderId: '185894325619',
    projectId: 'se7ety-8f530',
    authDomain: 'se7ety-8f530.firebaseapp.com',
    storageBucket: 'se7ety-8f530.firebasestorage.app',
    measurementId: 'G-LTT4E36DY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSthUaV8nLTTQqxNJXM21ygcZZXGnkQqE',
    appId: '1:185894325619:android:8cf733807fc4cc4ff38906',
    messagingSenderId: '185894325619',
    projectId: 'se7ety-8f530',
    storageBucket: 'se7ety-8f530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmKxFtzxNTmTB5_oiDK8hUXzEJpVTqq_k',
    appId: '1:185894325619:ios:2f0c22c1aff298fcf38906',
    messagingSenderId: '185894325619',
    projectId: 'se7ety-8f530',
    storageBucket: 'se7ety-8f530.firebasestorage.app',
    iosBundleId: 'com.example.se7etyGio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj5zfWVZqS9Dg5s0lu7v1tJfjZSZwd32E',
    appId: '1:185894325619:web:f0cbcade40750612f38906',
    messagingSenderId: '185894325619',
    projectId: 'se7ety-8f530',
    authDomain: 'se7ety-8f530.firebaseapp.com',
    storageBucket: 'se7ety-8f530.firebasestorage.app',
    measurementId: 'G-1KF7EXG3PM',
  );

}